---
server:
  address: "tcp://0.0.0.0:9091"

log:
  level: info

totp:
  issuer: {{ env "AUTHELIA_DOMAIN" }}

authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      key_length: 32
      salt_length: 16

access_control:
  default_policy: two_factor
  rules:
    - domain: '{{ (urlParse (env "AUTHELIA_AUTH_URL")).Host }}'
      policy: bypass

session:
  name: authelia_session
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - domain: {{ env "AUTHELIA_DOMAIN" }}
      authelia_url: {{ env "AUTHELIA_AUTH_URL" }}
      default_redirection_url: https://{{ env "AUTHELIA_DOMAIN" }}
  redis:
    host: authelia-redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  postgres:
    address: "tcp://authelia-db:5432"
    database: {{ env "AUTHELIA_POSTGRES_DATABASE" }}
    username: {{ env "AUTHELIA_POSTGRES_USER" }}

notifier:
  smtp:
    address: 'smtp://{{ env "AUTHELIA_SMTP_HOST" }}:{{ env "AUTHELIA_SMTP_PORT" }}'
    username: {{ env "AUTHELIA_SMTP_USERNAME" }}
    sender: 'Authelia <{{ env "AUTHELIA_SMTP_FROM" }}>'
    subject: "[Authelia] {title}"
    startup_check_address: {{ env "AUTHELIA_SMTP_FROM" }}
