services:
  adguard-home:
    image: adguard/adguardhome:v0.107.75
    container_name: adguard-home
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - ${ADGUARD_HOME_WORK_HOST_PATH}:${ADGUARD_HOME_WORK_CONTAINER_PATH}
      - ${ADGUARD_HOME_CONF_HOST_PATH}:${ADGUARD_HOME_CONF_CONTAINER_PATH}
    ports:
      - "${ADGUARD_HOME_DNS_PORT}:53/tcp"
      - "${ADGUARD_HOME_DNS_PORT}:53/udp"
      - "${ADGUARD_HOME_WEB_PORT}:${ADGUARD_HOME_WEB_PORT}/tcp"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${ADGUARD_HOME_WEB_PORT}/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    cpus: ${ADGUARD_HOME_CPUS}
    mem_limit: ${ADGUARD_HOME_MEM_LIMIT}

networks:
  default:
    name: adguard_home_network
