services:
  swiparr:
    image: ghcr.io/m3sserstudi0s/swiparr:1.5.1
    container_name: swiparr
    user: "${SWIPARR_UID}:${SWIPARR_GID}"
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=swiparr
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_PUBLIC_URL=${JELLYFIN_PUBLIC_URL}
      - USE_SECURE_COOKIES=${USE_SECURE_COOKIES}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
    volumes:
      - ${SWIPARR_DATA_HOST_PATH}:${SWIPARR_DATA_CONTAINER_PATH}
    ports:
      - "${SWIPARR_WEB_PORT}:4321"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:4321/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${SWIPARR_CPUS}
    mem_limit: ${SWIPARR_MEM_LIMIT}

networks:
  default:
    name: swiparr_network
