services:
  swiparr:
    image: ghcr.io/m3sserstudi0s/swiparr:1.4.0
    container_name: swiparr
    user: "${SWIPARR_UID}:${SWIPARR_GID}"
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
    environment:
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_PUBLIC_URL=${JELLYFIN_PUBLIC_URL}
      - USE_SECURE_COOKIES=${USE_SECURE_COOKIES}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
    volumes:
      - ./swiparr/data:/app/data
    ports:
      - 4321:4321
networks: {}
