services:
  seer:
    image: ghcr.io/seerr-team/seerr:v3.2.0
    init: true
    container_name: seer
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
    environment:
      TZ: ${SEER_TZ}
      LOG_LEVEL: ${SEER_LOG_LEVEL}
      PORT: ${SEER_CONTAINER_PORT}
    ports:
      - "${SEER_WEB_PORT}:${SEER_CONTAINER_PORT}"
    volumes:
      - ${SEER_CONFIG_HOST_PATH}:${SEER_CONFIG_CONTAINER_PATH}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${SEER_CONTAINER_PORT}/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    cpus: ${SEER_CPUS}
    mem_limit: ${SEER_MEM_LIMIT}
