services:
  navidrome:
    image: ghcr.io/navidrome/navidrome:0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
    container_name: navidrome
    user: "${NAVIDROME_UID}:${NAVIDROME_GID}"
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=navidrome
    environment:
      TZ: ${NAVIDROME_TZ}
      ND_MUSICFOLDER: ${NAVIDROME_MUSIC_CONTAINER_PATH}
      ND_DATAFOLDER: ${NAVIDROME_DATA_CONTAINER_PATH}
      ND_WELCOMEMESSAGE: ${NAVIDROME_WELCOME_MESSAGE}
    ports:
      - "${NAVIDROME_WEB_PORT}:4533"
    volumes:
      - ${NAVIDROME_DATA_HOST_PATH}:${NAVIDROME_DATA_CONTAINER_PATH}
      - ${NAVIDROME_MUSIC_HOST_PATH}:${NAVIDROME_MUSIC_CONTAINER_PATH}:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4533/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${NAVIDROME_CPUS}
    mem_limit: ${NAVIDROME_MEM_LIMIT}

networks:
  default:
    name: navidrome_network
