services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.3-ls256
    container_name: sabnzbd
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=sabnzbd
    environment:
      PUID: ${SABNZBD_UID}
      PGID: ${SABNZBD_GID}
      TZ: ${SABNZBD_TZ}
    ports:
      - "${SABNZBD_WEB_PORT}:8080"
    volumes:
      - ${SABNZBD_CONFIG_HOST_PATH}:${SABNZBD_CONFIG_CONTAINER_PATH}
      - ${SABNZBD_DOWNLOADS_HOST_PATH}:${SABNZBD_DOWNLOADS_CONTAINER_PATH}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${SABNZBD_CPUS}
    mem_limit: ${SABNZBD_MEM_LIMIT}

networks:
  default:
    name: sabnzbd_network
