services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.1
    container_name: sabnzbd
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
    environment:
      PUID: ${SABNZBD_UID}
      PGID: ${SABNZBD_GID}
      TZ: ${SABNZBD_TZ}
    ports:
      - "${SABNZBD_WEB_PORT}:8080"
    volumes:
      - ${SABNZBD_CONFIG_HOST_PATH}:${SABNZBD_CONFIG_CONTAINER_PATH}
      - ${SABNZBD_DOWNLOADS_HOST_PATH}:${SABNZBD_DOWNLOADS_CONTAINER_PATH}
      - ${SABNZBD_INCOMPLETE_DOWNLOADS_HOST_PATH}:${SABNZBD_INCOMPLETE_DOWNLOADS_CONTAINER_PATH}
    cpus: ${SABNZBD_CPUS}
    mem_limit: ${SABNZBD_MEM_LIMIT}
