services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1.10360-ls304
    container_name: radarr
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=radarr
    environment:
      PUID: ${RADARR_UID}
      PGID: ${RADARR_GID}
      TZ: ${RADARR_TZ}
    ports:
      - "${RADARR_WEB_PORT}:7878"
    volumes:
      - ${RADARR_CONFIG_HOST_PATH}:${RADARR_CONFIG_CONTAINER_PATH}
      - ${RADARR_MOVIES_HOST_PATH}:${RADARR_MOVIES_CONTAINER_PATH}
      - ${RADARR_DOWNLOADS_HOST_PATH}:${RADARR_DOWNLOADS_CONTAINER_PATH}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7878/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${RADARR_CPUS}
    mem_limit: ${RADARR_MEM_LIMIT}

networks:
  default:
    name: radarr_network
