services:
  vaultwarden-db:
    image: postgres:18.4-alpine3.24@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    container_name: vaultwarden-db
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=vaultwarden
    environment:
      POSTGRES_DB: ${VAULTWARDEN_POSTGRES_DATABASE}
      POSTGRES_USER: ${VAULTWARDEN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VAULTWARDEN_POSTGRES_PASSWORD}
      TZ: ${VAULTWARDEN_TZ}
    volumes:
      - ${VAULTWARDEN_POSTGRES_DATA_HOST_PATH}/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    cpus: ${VAULTWARDEN_POSTGRES_CPUS}
    mem_limit: ${VAULTWARDEN_POSTGRES_MEM_LIMIT}

  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.1
    container_name: vaultwarden
    user: "${VAULTWARDEN_UID}:${VAULTWARDEN_GID}"
    restart: unless-stopped
    depends_on:
      vaultwarden-db:
        condition: service_healthy
    labels:
      - docker-volume-backup.stop-during-backup=vaultwarden
    environment:
      TZ: ${VAULTWARDEN_TZ}
      DATABASE_URL: postgresql://${VAULTWARDEN_POSTGRES_USER}:${VAULTWARDEN_POSTGRES_PASSWORD}@vaultwarden-db:5432/${VAULTWARDEN_POSTGRES_DATABASE}
      DOMAIN: ${VAULTWARDEN_DOMAIN}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED}
      INVITATIONS_ALLOWED: ${VAULTWARDEN_INVITATIONS_ALLOWED}
      SMTP_HOST: ${VAULTWARDEN_SMTP_HOST}
      SMTP_PORT: ${VAULTWARDEN_SMTP_PORT}
      SMTP_SECURITY: ${VAULTWARDEN_SMTP_SECURITY}
      SMTP_USERNAME: ${VAULTWARDEN_SMTP_USERNAME}
      SMTP_PASSWORD: ${VAULTWARDEN_SMTP_PASSWORD}
      SMTP_FROM: ${VAULTWARDEN_SMTP_FROM}
      SMTP_FROM_NAME: ${VAULTWARDEN_SMTP_FROM_NAME}
      SSO_ENABLED: ${VAULTWARDEN_SSO_ENABLED}
      SSO_ONLY: ${VAULTWARDEN_SSO_ONLY}
      SSO_SIGNUPS_MATCH_EMAIL: ${VAULTWARDEN_SSO_SIGNUPS_MATCH_EMAIL}
      SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: ${VAULTWARDEN_SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION}
      SSO_PKCE: ${VAULTWARDEN_SSO_PKCE}
      SSO_SCOPES: ${VAULTWARDEN_SSO_SCOPES}
      SSO_AUTHORITY: ${VAULTWARDEN_SSO_AUTHORITY}
      SSO_CLIENT_ID: ${VAULTWARDEN_SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${VAULTWARDEN_SSO_CLIENT_SECRET}
    volumes:
      - ${VAULTWARDEN_DATA_HOST_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${VAULTWARDEN_WEB_PORT}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${VAULTWARDEN_CPUS}
    mem_limit: ${VAULTWARDEN_MEM_LIMIT}

networks:
  default:
    name: vaultwarden_network
