services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.8
    container_name: jellyfin
    user: "${JELLYFIN_UID}:${JELLYFIN_GID}"
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "107"
    labels:
      - docker-volume-backup.stop-during-backup=true
    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${JELLYFIN_TZ}
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PUBLISHED_SERVER_URL}
      JELLYFIN_CACHE_DIR: ${JELLYFIN_CACHE_DIR}
      LIBVA_DRIVER_NAME: iHD
    ports:
      - "${JELLYFIN_WEB_PORT}:8096"
      - "${JELLYFIN_HTTPS_PORT}:8920"
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_CACHE_PATH}:${JELLYFIN_CACHE_DIR}
      - ${JELLYFIN_MOVIES_SOURCE}:${JELLYFIN_MOVIES_TARGET}
      - ${JELLYFIN_SERIES_SOURCE}:${JELLYFIN_SERIES_TARGET}
    tmpfs:
      - ${JELLYFIN_TRANSCODE_TMPFS_PATH}
    cpus: ${JELLYFIN_CPUS}
    mem_limit: ${JELLYFIN_MEM_LIMIT}
