services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.10
    container_name: jellyfin
    user: "${JELLYFIN_UID}:${JELLYFIN_GID}"
    restart: unless-stopped
    devices:
      - ${JELLYFIN_GPU_DEVICE_HOST_PATH}:${JELLYFIN_GPU_DEVICE_CONTAINER_PATH}
    group_add:
      - "${JELLYFIN_VIDEO_GROUP_ID}"
      - "${JELLYFIN_RENDER_GROUP_ID}"
    labels:
      - docker-volume-backup.stop-during-backup=jellyfin
    environment:
      TZ: ${JELLYFIN_TZ}
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PUBLISHED_SERVER_URL}
      JELLYFIN_CACHE_DIR: ${JELLYFIN_CACHE_CONTAINER_PATH}
      LIBVA_DRIVER_NAME: iHD
    ports:
      - "${JELLYFIN_WEB_PORT}:8096"
      - "${JELLYFIN_HTTPS_PORT}:8920"
    volumes:
      - ${JELLYFIN_CONFIG_HOST_PATH}:${JELLYFIN_CONFIG_CONTAINER_PATH}
      - ${JELLYFIN_CACHE_HOST_PATH}:${JELLYFIN_CACHE_CONTAINER_PATH}
      - ${JELLYFIN_MOVIES_HOST_PATH}:${JELLYFIN_MOVIES_CONTAINER_PATH}
      - ${JELLYFIN_SERIES_HOST_PATH}:${JELLYFIN_SERIES_CONTAINER_PATH}
    tmpfs:
      - ${JELLYFIN_TRANSCODE_CONTAINER_PATH}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8096/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    cpus: ${JELLYFIN_CPUS}
    mem_limit: ${JELLYFIN_MEM_LIMIT}

networks:
  default:
    name: jellyfin_network
