services:
  firefly_iii_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: firefly_iii_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: firefly-iii-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: firefly-iii-backup-
    volumes:
      - ../../eggenberg-services/firefly-iii/firefly-iii/db:/backup/firefly_iii_db:ro
      - ../../eggenberg-services/firefly-iii/firefly-iii/upload:/backup/firefly_iii_upload:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/firefly-iii:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  bambuddy_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: bambuddy_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: bambuddy-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: bambuddy-backup-
    volumes:
      - ../../eggenberg-services/bambuddy/bambuddy/data:/backup/bambuddy_data:ro
      - ../../eggenberg-services/bambuddy/bambuddy/logs:/backup/bambuddy_logs:ro
      - ../../eggenberg-services/bambuddy/bambuddy/virtual_printer:/backup/bambuddy_virtual_printer:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/bambuddy:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  jellyfin_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: jellyfin_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: jellyfin-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: jellyfin-backup-
    volumes:
      - ${JELLYFIN_CONFIG_HOST_PATH}:/backup/jellyfin_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/jellyfin:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  swiparr_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: swiparr_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: swiparr-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: swiparr-backup-
    volumes:
      - ${SWIPARR_DATA_HOST_PATH}:/backup/swiparr_data:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/swiparr:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  sabnzbd_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: sabnzbd_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: sabnzbd-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: sabnzbd-backup-
    volumes:
      - ${SABNZBD_CONFIG_HOST_PATH}:/backup/sabnzbd_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/sabnzbd:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  seerr_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: seerr_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: seerr-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: seerr-backup-
    volumes:
      - ${SEERR_CONFIG_HOST_PATH}:/backup/seerr_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/seerr:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  radarr_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: radarr_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: radarr-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: radarr-backup-
    volumes:
      - ${RADARR_CONFIG_HOST_PATH}:/backup/radarr_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/radarr:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  sonarr_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: sonarr_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: sonarr-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: sonarr-backup-
    volumes:
      - ${SONARR_CONFIG_HOST_PATH}:/backup/sonarr_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/sonarr:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  jellystat_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: jellystat_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: jellystat-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: jellystat-backup-
    volumes:
      - ${JELLYSTAT_BACKUP_HOST_PATH}:/backup/jellystat_backup_data:ro
      - ${JELLYSTAT_POSTGRES_DATA_HOST_PATH}:/backup/jellystat_postgres_data:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/jellystat:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro

  home_assistant_backup:
    image: offen/docker-volume-backup:v2.48.0
    container_name: home_assistant_volume_backup
    restart: unless-stopped
    env_file:
      - backup.env
    environment:
      BACKUP_FILENAME: home-assistant-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: home-assistant-backup-
    volumes:
      - ${HOME_ASSISTANT_CONFIG_HOST_PATH}:/backup/home_assistant_config:ro
      - ${BACKUP_ROOT:-/mnt/default_pool/dockge/back}/home-assistant:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro
