services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.14.0@sha256:01540977dcf4c7b41b1159f34d68e4632f2658d62790e460ca65a42722b13c4a
    container_name: pocket-id
    restart: unless-stopped
    stop_grace_period: 30s
    labels:
      - docker-volume-backup.stop-during-backup=pocket-id
    environment:
      TZ: ${POCKET_ID_TZ}
      PUID: ${POCKET_ID_UID}
      PGID: ${POCKET_ID_GID}
      APP_URL: ${POCKET_ID_PUBLIC_APP_URL}
      TRUST_PROXY: ${POCKET_ID_TRUST_PROXY}
      ENCRYPTION_KEY: ${POCKET_ID_ENCRYPTION_KEY}
    volumes:
      - ${POCKET_ID_DATA_HOST_PATH}:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${POCKET_ID_WEB_PORT}:1411"
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${POCKET_ID_CPUS}
    mem_limit: ${POCKET_ID_MEM_LIMIT}

networks:
  default:
    name: pocket-id_network
