services:
  sonarr:
    image: linuxserver/sonarr:4.0.17.2952-ls312@sha256:0b5c4803f92456fb9b65bae8375716ea120b4ea17b3cced7da32b63f0085782b
    container_name: sonarr
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=sonarr
    environment:
      PUID: ${SONARR_UID}
      PGID: ${SONARR_GID}
      TZ: ${SONARR_TZ}
    ports:
      - "${SONARR_WEB_PORT}:8989"
    volumes:
      - ${SONARR_CONFIG_HOST_PATH}:${SONARR_CONFIG_CONTAINER_PATH}
      - ${SONARR_SERIES_HOST_PATH}:${SONARR_SERIES_CONTAINER_PATH}
      - ${SONARR_DOWNLOADS_HOST_PATH}:${SONARR_DOWNLOADS_CONTAINER_PATH}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8989/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpus: ${SONARR_CPUS}
    mem_limit: ${SONARR_MEM_LIMIT}

networks:
  default:
    name: sonarr_network
